USE DataWarehouse;
GO


-- Explore where customers are comming from

SELECT DISTINCT country
FROM gold.dim_customers;
GO

-- Explore all categories

select DISTINCT category, subcategory, product_name
FROM gold.dim_products
order by 1,2,3;
GO

-- Find first, last order and range betweeen them
SELECT 
MIN(order_date) as first_order_date,
MAX(order_date) as last_order_date, 
DATEDIFF(month, min(order_date), max(order_date)) as order_range_months
FROM gold.fact_sales;
GO

-- Find youngest and oldest customer

SELECT 
MIN(birth_date) as oldest_birth_date,
DATEDIFF(year, MIN(birth_date), GETDATE()) as odlest_age,
MAX(birth_date) as youngest_birth_date,
DATEDIFF(year, MAX(birth_date), GETDATE()) as youngest_age
FROM gold.dim_customers;
GO




-- Find total sales

select sum(sales_amount) as total_sales
from gold.fact_sales;
GO

-- Number of items sold

select sum(quantity) as total_quantity
from gold.fact_sales;
GO

-- Find average selling price

select avg(price) as avg_price
from gold.fact_sales;
GO

-- Calculate number of orders
select count(distinct order_key) as total_orders 
from gold.fact_sales;
GO

-- Calculate total number of products
select count(distinct product_name) as total_products
from gold.dim_products;
GO

-- Find the total number of customers
SELECT count(customer_key) as total_customers
FROM gold.dim_customers;
GO

-- Find the total number of customers that placed an order
SELECT count(distinct customer_key) as total_customers
FROM gold.fact_sales;
GO

-- Generate a general report 

select 'Total_sales' as measure_name, sum(sales_amount) as total_sales
from gold.fact_sales
UNION ALL
select 'Total Quantity', sum(quantity) as total_quantity
from gold.fact_sales
UNION ALL
select 'Average Price', avg(price) as avg_price
from gold.fact_sales
UNION ALL
select 'Total Nr. Orders', count(distinct order_key) as total_products
from gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products', count(distinct product_key) as total_customers
FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers', count(customer_key) as total_customers
FROM gold.dim_customers;
GO

--Find total customers by country

SELECT 
country,
count(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender

SELECT 
gender,
count(customer_key) as total_customers
FROM gold.dim_customers
GROUP BY gender;

-- Find total products by category

SELECT 
category,
count(product_key) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;



-- Find avg cost in each category

SELECT 
category,
avg(product_cost) as avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost;
GO

-- Find total revenue genereated for each category
select 
p.category,
sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key=p.product_key
group by p.category
order by total_revenue DESC;
GO



-- Find total revenue generated by each customer

select 
c.customer_key,
c.first_name,
c.last_name,
sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key=c.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_revenue DESC;

-- What is the distribution of sold items across countries
select
c.country,
sum(s.quantity) as total_items_sold
from gold.fact_sales s
left join gold.dim_customers c
on c.customer_key=s.customer_key
group by c.country
order by total_items_sold desc;


-- 5 products with highest revenue

select top 5
p.product_name,
sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key=p.product_key
group by p.product_name
order by total_revenue DESC;


select * 
from (
select
p.product_name,
sum(s.sales_amount) as total_revenue,
row_number() over(order by sum(s.sales_amount) desc) as rank_products
from gold.fact_sales s
left join gold.dim_products p
on s.product_key=p.product_key
group by p.product_name) t
where rank_products<=5;



-- 5 worst performing products in terms of sales
select top 5
p.product_name,
sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_products p
on s.product_key=p.product_key
group by p.product_name
order by total_revenue asc;


-- Find top 10 customers with highest revenue
select top 10
c.customer_key,
c.first_name,
c.last_name,
sum(s.sales_amount) as total_revenue
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key=c.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_revenue desc;

select top 3
c.customer_key,
c.first_name,
c.last_name,
count(distinct order_key) as total_orders
from gold.fact_sales s
left join gold.dim_customers c
on s.customer_key=c.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_orders asc;

